version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: exampledatabase
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    ports:
      - "1:1"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    ports:
      - "1:1"
    depends_on:
      - mysql_db
    environment:
      DB_HOST: mysql_db
      DB_USER: exampleuser
      DB_PASSWORD: examplepassword
      DB_NAME: exampledatabase
      EMAIL_ADDRESS: exampleaddress
      EMAIL_PASSWORD: examplepassword
volumes:
  mysql_data: